format_version: 10
pipelines:
  TestPipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-69b213b:
        git: https://github.com/anthonysteele95/gocd-example
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - unit-tests:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run-unit-test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - test
                command: ./gradlew
                run_if: passed
